# Generated by Django 4.0.4 on 2022-05-11 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('pic', models.FileField(blank=True, null=True, upload_to='Product')),
                ('discount', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.selleruser')),
            ],
        ),
    ]
